### ISSUE TITLE
Smart Cookie should fail when different server key is provided when log_interest happen.

### ISSUE THREAD

**Issue by S0c5** [sine-fdn/tandem#36] opened 2023-01-21 21:27 UTC
# The problem

First of all, thanks for such an amazing project, I have enjoyed thinking about how to implement this in a real-world case, however, running the example of a smart cookie and modifying the `Tandem.toml` to include a different key in the `init` and after the `log_interest` this should fail with `LogResult::InvalidSignature` but it doesn't, I'd like to know if its something i'm doing is wrong!

thanks in advance.

## Tandem Toml

```Tandem.toml
[handlers.init]
_ = "SigningKey { key: [ 1u8,  2u8,  4u8, 4u8,  5u8,  6u8, 7u8,  8u8,  9u8, 10u8, 11u8, 12u8, 13u8, 14u8, 15u8, 17u8] }"

[handlers.log_interest]
article1 = "WebsiteVisit { key: SigningKey { key: [1u8; 16] }, interest: UserInterest::Luxury }"
article2 = "WebsiteVisit { key: SigningKey { key: [1u8; 16] }, interest: UserInterest::Politics }"
article3 = "WebsiteVisit { key: SigningKey { key: [1u8; 16] }, interest: UserInterest::Cars }"
article4 = "WebsiteVisit { key: SigningKey { key: [1u8; 16] }, interest: UserInterest::Sports }"
article5 = "WebsiteVisit { key: SigningKey { key: [255u8; 16] }, interest: UserInterest::Politics }"

[handlers.decide_ad]
_ = "SigningKey { key: [ 1u8,  2u8,  3u8, 4u8,  5u8,  6u8, 7u8,  8u8,  9u8, 10u8, 11u8, 12u8, 13u8, 14u8, 15u8, 16u8] }"

```

## Modified Test

I modified this test to include `article5` as log_interest which have a different signature that was used when was called the `init` function

```rust
#![cfg(target_arch = "wasm32")]

// use std::{include_str, println};

use js_sys::Reflect;
use tandem_http_client::{compute, MpcData, MpcProgram};
use wasm_bindgen::prelude::*;
use wasm_bindgen_test::wasm_bindgen_test;

#[cfg(target_arch = "wasm32")]
wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen]
extern "C" {
    // Use `js_namespace` here to bind `console.log(..)` instead of just
    // `log(..)`
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen_test]
async fn test() {
    console_log::init().expect("Could not init console_log");
    let url = "http://127.0.0.1:8000";

    
    let smart_cookie_prg = include_str!("smart_cookie_setup/program.garble.rs");
    let function = "init".to_string();
    let program = MpcProgram::new(smart_cookie_prg.to_string(), function)
        .expect("Could not parse source code");
    let metadata = "_";
    let my_input =
        MpcData::from_string(&program, "()".to_string()).unwrap_or_else(|e| panic!("{e}"));
    let mut user_state = compute(url.to_string(), metadata.to_string(), program, my_input)
        .await
        .unwrap_or_else(|e| panic!("{e}"));

    log(user_state.to_literal_string().as_ref());

    let function = "log_interest".to_string();

    let program = MpcProgram::new(smart_cookie_prg.to_string(), function)
        .expect("Could not parse source code");


    let metadata = "article5";
    let log_result = compute(
        url.to_string(),
        metadata.to_string(),
        program.clone(),
        user_state,
    )
    .await
    .unwrap_or_else(|e| panic!("{e}"))
    .to_literal()
    .unwrap_or_else(|e| panic!("{e}"));

    
    let log_result = Reflect::get(&log_result, &"Enum".into()).unwrap_or_else(|e| panic!("{e:?}"));

    
    let log_result_enum_name = Reflect::get_u32(&log_result, 0).unwrap_or_else(|e| panic!("{e:?}"));

    assert_eq!(log_result_enum_name, JsValue::from("LogResult"));

    let log_result_enum_variant =
        Reflect::get_u32(&log_result, 1).unwrap_or_else(|e| panic!("{e:?}"));
    assert_eq!(log_result_enum_variant, JsValue::from("Ok"));
    let log_result = Reflect::get_u32(&log_result, 2).unwrap_or_else(|e| panic!("{e:?}"));
    let log_result = Reflect::get(&log_result, &"Tuple".into()).unwrap_or_else(|e| panic!("{e:?}"));
    let log_result = Reflect::get_u32(&log_result, 0).unwrap_or_else(|e| panic!("{e:?}"));
    user_state = MpcData::from_object(&program, log_result).unwrap_or_else(|e| panic!("{e}"));

    let function = "decide_ad".to_string();
    let program = MpcProgram::new(smart_cookie_prg.to_string(), function)
        .expect("Could not parse source code");
    let metadata = "_";
    let ad_decision = compute(url.to_string(), metadata.to_string(), program, user_state)
        .await
        .unwrap_or_else(|e| panic!("{e}"));
    log(ad_decision.to_literal_string().as_ref());
    // assert!(ad_decision.to_literal_string().contains("Sports"));
}
```

**Comment by fkettelhoit** [comment] 2023-01-25 19:20
Hey David, thanks for your interest in the project!

You are absolutely right, the signature function used in the test was broken (due to a refactoring after changing the semantics of the Garble language) and the key did not actually have any effect on the resulting signature.

I have now fixed the signature function and added a test similar to the one you were using, can you check whether the issue is resolved for you on the [fix-issue-4-smart-cookie-signature](https://github.com/sine-fdn/tandem/tree/fix-issue-4-smart-cookie-signature) branch?

**Closed as completed** 2023-02-06 09:57 UTC
